language: node_js

node_js:
  - "0.12"
  - "0.10"

before_script:
  - "sh -e scripts/start_server.sh"
  - sleep 5

script: "phantomjs test/dev/phantom.js && node scripts/makeProductionReady.js"

sudo: false